name: app_flutter_example
description: Juno App Flutter
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_app:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  
flutter:
  uses-material-design: true